import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const root=new URL('../../',import.meta.url).pathname;
const base=fs.readFileSync(root+'/supabase/celebration_guestbook.sql','utf8');
const patch=fs.readFileSync(root+'/supabase/celebration_guestbook_refinements.sql','utf8');
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.actor',true),'')::uuid$$;
create table admin_users(user_id uuid);
create table storage.objects(bucket_id text,name text);
create table storage.buckets(id text,file_size_limit bigint,allowed_mime_types text[]);
insert into storage.buckets values ('celebration-photos',10485760,array['image/jpeg']);
create function public.subscribe_to_updates(text,text,text) returns void language sql as $$select$$;
${base.slice(base.indexOf('create table if not exists public.celebration_access_tokens'),base.indexOf('create index if not exists celebration_guestbook_created_at_idx'))}
${base.slice(base.indexOf('create view public.celebration_guestbook_public'),base.indexOf('create or replace function public.validate_celebration_access_token'))}
create function public.validate_celebration_access_token(raw_token text) returns table(access_token_id uuid,label text) language sql as $$select id,label from celebration_access_tokens where token_hash=raw_token and is_active$$;
${base.slice(base.indexOf('create or replace function public.admin_list_celebration_guestbook()'),base.indexOf('alter table public.celebration_access_tokens enable'))}
${base.slice(base.indexOf('create or replace function public.can_read_celebration_photo('),base.indexOf('-- Optional selfie station uploads'))}
insert into celebration_access_tokens(id,label,token_hash) values('11111111-1111-1111-1111-111111111111','test','valid');
insert into celebration_guestbook(id,name,email,city,state_region,latitude,longitude,photo_bucket,photo_path) values ('22222222-2222-2222-2222-222222222222','Existing guest','private@example.com','San Clemente','CA',33.4269,-117.6119,'celebration-photos','celebration/existing.jpg');`);
await db.exec(patch);
const before=(await db.query('select * from celebration_guestbook')).rows[0];
assert.equal(before.media_approved,true);assert.equal(Number(before.latitude),33.4269);
const rad=x=>x*Math.PI/180;
const deltaLat=rad(Number(before.display_latitude)-33.4269),deltaLon=rad(Number(before.display_longitude)+117.6119);
const a=Math.sin(deltaLat/2)**2+Math.cos(rad(33.4269))*Math.cos(rad(Number(before.display_latitude)))*Math.sin(deltaLon/2)**2;
const distance=6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));assert(distance>7.9 && distance<30.1);
await db.exec(patch);
await db.exec("update celebration_guestbook set memory='Edited story',is_hidden=true");
const after=(await db.query('select * from celebration_guestbook')).rows[0];
assert.equal(after.display_latitude,before.display_latitude);assert.equal(after.display_longitude,before.display_longitude);
assert.equal((await db.query('select * from celebration_guestbook_public')).rows.length,0);
await db.exec("update celebration_guestbook set is_hidden=false");
await db.exec("insert into storage.objects values ('celebration-photos','celebration/photo.jpg'),('celebration-photos','celebration/video.mp4')");
const submit=(path,memory='')=>db.query("select * from submit_celebration_guestbook_v2(raw_token=>'valid',guest_name=>'Returning Guest',guest_email=>'private2@example.com',guest_city=>'Austin',guest_state_region=>'TX',guest_country=>'United States',guest_relationship=>'',guest_came_with=>'',guest_memory=>$1,guest_photo_bucket=>'celebration-photos',guest_photo_path=>$2,guest_photo_mime_type=>$3,guest_latitude=>30.2672,guest_longitude=>-97.7431)",[memory,path,path.endsWith('mp4')?'video/mp4':'image/jpeg']);
assert.equal((await submit('celebration/photo.jpg','Immediate story')).rows[0].status,'success');
assert.equal((await submit('celebration/video.mp4')).rows[0].status,'success');
assert.equal((await submit('celebration/video.mp4')).rows[0].status,'duplicate');
let rows=(await db.query("select * from celebration_guestbook_public where name='Returning Guest'")).rows;
assert.equal(rows.length,2);assert(rows.every(r=>r.photo_path===null));assert(rows.some(r=>r.memory==='Immediate story'));assert(rows.every(r=>!('email' in r)));
assert.equal((await db.query("select can_read_celebration_photo('celebration-photos','celebration/video.mp4') ok")).rows[0].ok,false);
const id=(await db.query("select id from celebration_guestbook where photo_path='celebration/video.mp4'")).rows[0].id;
await assert.rejects(db.query('select admin_moderate_celebration_guestbook(entry_id=>$1,guest_media_approved=>true)',[id]),/Admin authorization/);
await db.exec("insert into admin_users values ('33333333-3333-3333-3333-333333333333'); set test.actor='33333333-3333-3333-3333-333333333333'");
await db.query('select admin_moderate_celebration_guestbook(entry_id=>$1,guest_media_approved=>true)',[id]);
assert.equal((await db.query("select can_read_celebration_photo('celebration-photos','celebration/video.mp4') ok")).rows[0].ok,true);
const adminRows=(await db.query('select * from admin_list_celebration_guestbook()')).rows;assert(adminRows.some(r=>r.id===id && r.media_approved));
await db.query('select admin_moderate_celebration_guestbook(entry_id=>$1,guest_is_hidden=>true)',[id]);
assert.equal((await db.query("select can_read_celebration_photo('celebration-photos','celebration/video.mp4') ok")).rows[0].ok,false);
await db.query('select admin_moderate_celebration_guestbook(entry_id=>$1,guest_is_hidden=>false)',[id]);
await db.query('select admin_moderate_celebration_guestbook(entry_id=>$1,guest_is_deleted=>true)',[id]);
assert.equal((await db.query('select * from celebration_guestbook_public where id=$1',[id])).rows.length,0);
assert.equal(Number((await db.query('select * from celebration_guestbook_stats()')).rows[0].people_here),2);
await db.exec('set role anon');
await assert.rejects(db.query('select * from celebration_guestbook'),/permission denied/);
assert((await db.query('select * from celebration_guestbook_public')).rows.every(r=>!('email' in r)));
console.log('PASS: existing-media preservation; stable randomized backfill and radius; rerun safety; immediate text; optional story; photo/video approval; admin hide/unhide/delete; no duplicate uploads or attendance; no public emails.');
await db.close();
